version: '3.8'

services:
  ffc-ahwr-frontend:
    build:
      context: .
      target: production
    image: ffc-ahwr-frontend
    container_name: ffc-ahwr-frontend
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-frontend-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      APPLICATIONREQUEST_QUEUE_ADDRESS: ${APPLICATIONREQUEST_QUEUE_ADDRESS:-ffc-ahwr-application-request}${MESSAGE_QUEUE_SUFFIX}
      APPLICATIONRESPONSE_QUEUE_ADDRESS: ${APPLICATIONRESPONSE_QUEUE_ADDRESS:-ffc-ahwr-application-response}${MESSAGE_QUEUE_SUFFIX}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      ELIGIBILITYREQUEST_QUEUE_ADDRESS: ${ELIGIBILITYREQUEST_QUEUE_ADDRESS:-ffc-ahwr-eligibility-request}${MESSAGE_QUEUE_SUFFIX}
      ELIGIBILITYRESPONSE_QUEUE_ADDRESS: ${ELIGIBILITYRESPONSE_QUEUE_ADDRESS:-ffc-ahwr-eligibility-response}${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
