version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-frontend:
    build:
      target: development
    depends_on:
      - ffc-ahwr-frontend-azurite
      - redis
    image: ffc-ahwr-frontend-development
    container_name: ffc-ahwr-frontend-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-ahwr-frontend-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.16.0
    command: "azurite --loose --skipApiVersionCheck --queueHost 0.0.0.0 --blobHost 0.0.0.0 --tableHost 0.0.0.0"
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  azurite_data:
  redis_data:
