version: '3.8'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-ahwr-frontend:
    build:
      target: development
    image: ffc-ahwr-frontend-development
    container_name: ffc-ahwr-frontend-test
    command: npm run test
    volumes:
      - ./test-output:/home/node/test-output
