{{- include "ffc-helm-library.container-config-map" (list . "ffc-ahwr-frontend.config-map") -}}
{{- define "ffc-ahwr-frontend.config-map" -}}
data:
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  APPLICATIONREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationRequestQueueAddress }}
  APPLICATIONRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.applicationResponseQueueAddress }}
  ELIGIBILITYREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.eligibilityRequestQueueAddress }}
  ELIGIBILITYRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.eligibilityResponseQueueAddress }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey}}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  NODE_ENV: {{ quote .Values.environment }}
  NOTIFY_TEMPLATE_ID_FARMER_APPLY_LOGIN: {{ quote .Values.container.notifyTemplateIdFarmerApplyLogin }}
  NOTIFY_TEMPLATE_ID_FARMER_CLAIM_LOGIN: {{ quote .Values.container.notifyTemplateIdFarmerClaimLogin }}
  NOTIFY_TEMPLATE_ID_VET_LOGIN: {{ quote .Values.container.notifyTemplateIdVetLogin }}
  PORT: {{ quote .Values.container.port }}
  {{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  {{- end }}
  {{- if .Values.pr }}
  REDIS_PARTITION: {{ .Values.container.redisPartition }}-{{ .Values.pr }}
  {{ else }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
  {{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  SERVICE_URI: {{ quote .Values.container.serviceUri }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
{{- end -}}
