environment: development
name: ffc-ahwr-frontend
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-frontend

labels: {}

appInsights:
  key:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-ahwr-frontend-config-map

containerSecret:
  name: ffc-ahwr-frontend-container-secret
  type: Opaque

container:
  applicationRequestQueueAddress: ffc-sfi-application-request
  applicationResponseQueueAddress: ffc-sfi-application-response
  eligibilityRequestQueueAddress: ffc-sfi-eligibility-request
  eligibilityResponseQueueAddress: ffc-sfi-eligibility-response
  imagePullPolicy: IfNotPresent
  limitCpu: 40m
  limitMemory: 40Mi
  messageQueueHost: namespace.servicebus.windows.net
  port: 3000
  requestCpu: 10m
  requestMemory: 10Mi

deployment:
  minReadySeconds: 0
  priorityClassName: default
  replicas: 1
  restartPolicy: Always

ingress:
  class: nginx
  endpoint: ffc-ahwr-frontend
  server: example.com

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  path: /healthz
  periodSeconds: 10
  port: 3000

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  path: /healthy
  periodSeconds: 10
  port: 3000

service:
  port: 80
  type: ClusterIP
