environment: development
name: ffc-ahwr-frontend
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-frontend

labels: {}

aadPodIdentity: true

appInsights:
  key:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-ahwr-frontend-config-map

containerSecret:
  name: ffc-ahwr-frontend-container-secret
  type: Opaque

container:
  applicationRequestQueueAddress: ffc-ahwr-application-request
  applicationResponseQueueAddress: ffc-ahwr-application-response
  fetchApplicationRequestQueueAddress: ffc-ahwr-fetch-application-request
  fetchAapplicationResponseQueueAddress: ffc-ahwr-fetch-application-response
  azureStorageConnectionString:
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  eligibilityRequestQueueAddress: ffc-ahwr-eligibility-request
  eligibilityResponseQueueAddress: ffc-ahwr-eligibility-response
  imagePullPolicy: IfNotPresent
  limitCpu: 120m
  limitMemory: 200Mi
  messageQueueHost: namespace.servicebus.windows.net
  notifyApiKey:
  notifyTemplateIdApplicationComplete:
  notifyTemplateIdFarmerApplyLogin:
  notifyTemplateIdFarmerClaimLogin:
  notifyTemplateIdVetLogin:
  port: 3000
  requestCpu: 100m
  requestMemory: 200Mi
  redisHostname: redis-hostname.default
  redisPartition: ffc-ahwr-frontend
  redisPassword: redis
  redisPort: 6379
  serviceUri:

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 2
  priorityClassName: default
  replicas: 1
  restartPolicy: Always

ingress:
  class: nginx
  endpoint: ffc-ahwr-frontend
  server: value.replaced.from.app.config

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  path: /healthz
  periodSeconds: 10
  port: 3000

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  path: /healthy
  periodSeconds: 10
  port: 3000

service:
  port: 80
  type: ClusterIP
